os: linux
dist: focal
language: shell
services:
  - docker

before_install:
  - docker build -t $YOUR_DOCKERHUB_USERNAME/flaskdemo .

script:
  - docker images $YOUR_DOCKERHUB_USERNAME/flaskdemo

before_deploy:
  - docker login -u $YOUR_DOCKERHUB_USERNAME -p $YOUR_DOCKERHUB_PASSWORD

deploy:
  provider: script
  script: docker push $YOUR_DOCKERHUB_USERNAME/flaskdemo
  on:
    branch: master
